apiVersion: v1
kind: policy
metadata:
  id: "pol-001"
  name: "Policy 001"
  description: "Descripcion de la policy"
  domain: "DBB"
  owner: "equipo-x"
  version: "1.0.0"
  status: "active"
spec:
  attributes:
    - "channel"
    - "transactionCode"
  combiningAlgorithm: "deny-overrides"
  rules:
    - id: "0120"
      version: "1.0.0"
