apiVersion: abac.galatea.bancolombia.com/v1
kind: AttributeProvider
metadata:
  id: ap-jwt-validation
  name: Proveedor de atributos de validación JWT
  version: 1.0.0
  owner: identity-security
  status: ACTIVE
spec:
  resolver:
    type: http
    protocol: https
    timeout: 15000
    operation:
      method: POST
      url: https://.../transactionalRiskAssessment
    requestTemplate: "{ ... }"
  security:
    credential:
      type: client-credentials
      apic: nu0051001-d2b-dev-banking-core-dbb
      digitalCertificate: nu0051001-...-multi-context
  provides:
    - attribute: authentication.token.valid
      dataType: boolean
  inputMapping:
    body.token: $.request.headers.Authorization
  responseMappings:
    - when: { statusCode: 200 }
      attributes: { authentication.token.valid: true, authentication.token.status: VALID }
  defaultResponseMappings:
    authentication.token.valid: false
  failureHandling:
    timeout: { result: false, reasonCode: AUTH001_TIMEOUT }

