apiVersion: abac.galatea.bancolombia.com/v1
kind: PolicyAssignment
metadata:
  id: pass-payment-authentication
  name: Control de acceso a pagos
  description: Es un grupo de políticas de de pagos.
  domain: payments
  owner: payments-security
  version: 1.0.0
  status: ACTIVE
spec:
  channel: "DBB"
  transactionCode: "0120"
  target:
    anyOf:
    - allOf:
      - attribute: resource.path
        type: string
        operator: ends-with
        value: "/api/v1/security-filters/ds-ms-dr-nequi/transfer-registered-nequi"
      - attribute: action.httpMethod
        type: string
        operator: equals
        value: POST
    - allOf:
      - attribute: resource.path
        type: string
        operator: ends-with
        value: "/api/v1/mcp/ds-ms-dr-nequi/transfer-registered-nequi"
      - attribute: action.mcpMethod
        type: string
        operator: equals
        value: tools/call
      - attribute: resource.mcpToolName
        type: string
        operator: equals
        value: checkCustomerControlLists
      - attribute: resource.count
        type: integer
        operator: equals
        value: 1
      - attribute: resource.dec
        type: decimal
        operator: greater-than
        value: 1.5

  defaultDecision: "Deny"
  combiningAlgorithm: "deny-unless-permit"
  policySets:
    - id: policyset-payment-authentication
      version: 1.0.0
